// =========================================
// 1-to-1 WebRTC calls
// =========================================
(function () {
    const ICE_SERVERS = [
        { urls: "stun:stun.l.google.com:19302" },
        { urls: "stun:stun1.l.google.com:19302" },
        { urls: "stun:stun.cloudflare.com:3478" }
    ];
    let channel=null, pc=null, localStream=null, remoteStream=null;
    let callId=null, peerId=null, peerName="Пользователь", chatId=null, mode="audio", role=null;
    let pendingOffer=null, pendingIce=[], timer=null, startedAt=0;
    const $=id=>document.getElementById(id);

    function ensureUi(){
        if($( "chatCallV2" )) return;
        const style=document.createElement("style");
        style.textContent=`
        #chatCallV2{position:fixed;inset:0;z-index:30000;background:rgba(10,8,7,.96);display:none;align-items:center;justify-content:center;padding:16px;color:#fff}
        #chatCallV2.open{display:flex}.cv2-card{width:min(560px,100%);height:min(760px,100%);background:linear-gradient(160deg,#211813,#523726);border-radius:24px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 24px 80px rgba(0,0,0,.55)}
        .cv2-head{text-align:center;padding:25px 18px 14px}.cv2-name{font-size:22px;font-weight:800}.cv2-status{margin-top:7px;color:#eadbce;font-size:14px}.cv2-media{flex:1;min-height:230px;background:#0c0b0a;position:relative;display:flex;align-items:center;justify-content:center}.cv2-avatar{font-size:78px}.cv2-remote{display:none;width:100%;height:100%;object-fit:cover}.cv2-local{display:none;position:absolute;right:14px;top:14px;width:115px;height:165px;object-fit:cover;border-radius:14px;background:#111;border:1px solid rgba(255,255,255,.3)}
        .cv2-incoming{display:none;justify-content:center;gap:18px;padding:20px}.cv2-incoming button{border:0;border-radius:999px;padding:14px 25px;font-weight:800;font-size:15px;cursor:pointer}.cv2-accept{background:#21ef62;color:#062b11}.cv2-reject{background:#e33d3d;color:#fff}.cv2-controls{display:none;justify-content:center;gap:14px;padding:20px;flex-wrap:wrap}.cv2-btn{width:54px;height:54px;border:0;border-radius:50%;background:#6c503d;color:#fff;font-size:22px;cursor:pointer}.cv2-btn.red{background:#e33d3d}.cv2-btn.green{background:#21ef62;color:#062b11}
        .chat-call-button{display:none!important;width:38px;height:38px;min-width:38px;padding:0;border:0;border-radius:50%;align-items:center;justify-content:center;cursor:pointer;box-shadow:0 4px 12px rgba(0,0,0,.18);transition:transform .15s ease,filter .15s ease}.chat-call-button:hover{transform:scale(1.06);filter:brightness(1.08)}.chat-call-audio{background:#21ef62;color:#062b11}.chat-call-video{background:#7f1d1d;color:#fff}
        .call-icon-video{position:relative;width:18px;height:14px;border:2px solid currentColor;border-radius:3px;display:block}.call-icon-video:after{content:"";position:absolute;right:-8px;top:2px;border-left:7px solid currentColor;border-top:4px solid transparent;border-bottom:4px solid transparent}.call-icon-phone{font-size:20px;font-weight:900;line-height:1;display:block;transform:rotate(-18deg)}
        @media(max-width:700px){#chatCallV2{padding:0}.cv2-card{width:100%;height:100%;border-radius:0}.cv2-media{min-height:0}.chat-call-button{width:38px;height:38px;min-width:38px}}
        `;
        document.head.appendChild(style);
        const root=document.createElement("div");root.id="chatCallV2";
        root.innerHTML=`<div class="cv2-card"><div class="cv2-head"><div class="cv2-name" id="cv2Name">Пользователь</div><div class="cv2-status" id="cv2Status">Подключение...</div></div><div class="cv2-media"><div class="cv2-avatar" id="cv2Avatar">📞</div><video class="cv2-remote" id="cv2Remote" autoplay playsinline></video><video class="cv2-local" id="cv2Local" autoplay playsinline muted></video></div><div class="cv2-incoming" id="cv2Incoming"><button class="cv2-reject" id="cv2Reject">Отклонить</button><button class="cv2-accept" id="cv2Accept">Принять</button></div><div class="cv2-controls" id="cv2Controls"><button class="cv2-btn" id="cv2Mute" title="Микрофон">🎙️</button><button class="cv2-btn" id="cv2VideoControl" title="Камера">📹</button><button class="cv2-btn" id="cv2Speaker" title="Динамик">🔊</button><button class="cv2-btn red" id="cv2Hangup" title="Завершить">📞</button></div></div>`;
        document.body.appendChild(root);
        $("cv2Reject").onclick=rejectIncoming;$("cv2Accept").onclick=acceptIncoming;$("cv2Hangup").onclick=()=>end(true);$("cv2Mute").onclick=toggleMute;$("cv2VideoControl").onclick=toggleVideo;$("cv2Speaker").onclick=toggleSpeaker;
    }
    function setStatus(t){if($("cv2Status"))$("cv2Status").textContent=t}
    function show(v){ensureUi();$("chatCallV2")?.classList.toggle("open",v)}
    function clearTimer(){if(timer)clearInterval(timer);timer=null;startedAt=0}
    function startTimer(){clearTimer();startedAt=Date.now();timer=setInterval(()=>{const s=Math.floor((Date.now()-startedAt)/1000);setStatus(`${mode==="video"?"Видеозвонок":"Звонок"} • ${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`)},1000)}
    async function send(type,payload={}){if(!callId||!chatId||!peerId||!window.currentUser?.id)return false;const {error}=await window.supabaseClient.from("call_signals").insert({chat_id:Number(chatId),sender_id:window.currentUser.id,recipient_id:peerId,call_id:callId,signal_type:type,payload});if(error){console.error("Ошибка сигнала звонка:",error);return false}return true}
    async function peerForChat(){const id=Number(currentChatId);if(!id)return null;const {data,error}=await window.supabaseClient.rpc("get_private_chat_peer",{p_chat_id:id});if(error){console.error("Ошибка определения собеседника:",error);return null}return data?.[0]||null}
    async function sendCallPush(){try{await window.supabaseClient.functions.invoke("send-call-push",{body:{chatId:Number(chatId),recipientId:peerId,callId,mode}})}catch(e){console.warn("Push звонка не отправлен:",e)}}
    function buildPeer(){if(pc){try{pc.close()}catch{}}remoteStream=new MediaStream();pc=new RTCPeerConnection({iceServers:ICE_SERVERS});pendingIce=[];pc.onicecandidate=e=>{if(e.candidate)void send("ice",{candidate:e.candidate.toJSON()})};pc.ontrack=e=>{if(!remoteStream.getTracks().some(t=>t.id===e.track.id))remoteStream.addTrack(e.track);const v=$("cv2Remote");if(v){v.srcObject=remoteStream;v.style.display=mode==="video"?"block":"none"}if($("cv2Avatar"))$("cv2Avatar").style.display=mode==="video"?"none":"block"};pc.onconnectionstatechange=()=>{const s=pc?.connectionState;if(s==="connected"){setStatus(mode==="video"?"Видеозвонок":"Звонок");startTimer()}if(s==="failed"){setStatus("Не удалось установить соединение");setTimeout(()=>end(false),1500)}if(s==="disconnected"){setStatus("Соединение потеряно");setTimeout(()=>end(false),2000)}};localStream?.getTracks().forEach(t=>pc.addTrack(t,localStream))}
    async function getMedia(){if(!navigator.mediaDevices?.getUserMedia)throw new Error("getUserMedia недоступен");localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:mode==="video"});const v=$("cv2Local");if(v){v.srcObject=localStream;v.style.display=mode==="video"?"block":"none"}}
    async function addIce(c){if(!pc||!c)return;if(pc.remoteDescription){try{await pc.addIceCandidate(c)}catch(e){console.warn("ICE:",e)}}else pendingIce.push(c)}
    async function flushIce(){for(const c of pendingIce.splice(0)){try{await pc?.addIceCandidate(c)}catch{}}}
    async function handleSignal(s){if(!s||!window.currentUser?.id||s.recipient_id!==window.currentUser.id)return;if(s.signal_type==="offer"){if(callId&&callId!==s.call_id)return;if(callId===s.call_id&&role==="callee")return;callId=s.call_id;chatId=Number(s.chat_id);peerId=s.sender_id;peerName=s.payload?.callerName||"Пользователь";mode=s.payload?.mode==="video"?"video":"audio";role="callee";pendingOffer=s.payload?.description||null;ensureUi();$("cv2Name").textContent=peerName;$("cv2Avatar").textContent=mode==="video"?"📹":"📞";$("cv2Incoming").style.display="flex";$("cv2Controls").style.display="none";setStatus(mode==="video"?"Входящий видеозвонок":"Входящий звонок");show(true);return}if(s.call_id!==callId)return;if(s.signal_type==="answer"&&pc){await pc.setRemoteDescription(s.payload.description);await flushIce()}else if(s.signal_type==="ice")await addIce(s.payload?.candidate);else if(s.signal_type==="reject"){setStatus("Звонок отклонён");setTimeout(()=>end(false),700)}else if(s.signal_type==="hangup"){setStatus("Собеседник завершил звонок");setTimeout(()=>end(false),700)}}
    async function subscribe(){if(channel||!window.supabaseClient||!window.currentUser?.id)return;channel=window.supabaseClient.channel(`call-v2-${window.currentUser.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"call_signals",filter:`recipient_id=eq.${window.currentUser.id}`},p=>void handleSignal(p.new)).subscribe(s=>{if(s==="CHANNEL_ERROR"||s==="TIMED_OUT"){channel=null;setTimeout(subscribe,1500)}});setTimeout(recoverOffer,500)}
    async function recoverOffer(){if(!window.currentUser?.id||callId)return;const since=new Date(Date.now()-60000).toISOString();const {data,error}=await window.supabaseClient.from("call_signals").select("chat_id,sender_id,recipient_id,call_id,signal_type,payload,created_at").eq("recipient_id",window.currentUser.id).eq("signal_type","offer").gte("created_at",since).order("created_at",{ascending:false}).limit(1);if(!error&&data?.[0])await handleSignal(data[0])}
    async function startCall(modeArg){if(!navigator.mediaDevices?.getUserMedia||!window.RTCPeerConnection){alert("Этот браузер не поддерживает звонки.");return}if(!window.currentUser?.id||!currentChatId){alert("Сначала откройте личный чат.");return}const peer=await peerForChat();if(!peer?.user_id){alert("Звонки доступны только в личном чате один-на-один.");return}await end(false);chatId=Number(currentChatId);peerId=peer.user_id;peerName=peer.username||"Пользователь";mode=modeArg==="video"?"video":"audio";role="caller";callId=crypto.randomUUID();try{ensureUi();$("cv2Name").textContent=peerName;$("cv2Avatar").textContent=mode==="video"?"📹":"📞";$("cv2Incoming").style.display="none";$("cv2Controls").style.display="flex";setStatus("Запрашиваем доступ к "+(mode==="video"?"камере и микрофону":"микрофону")+"…");show(true);await getMedia();buildPeer();const offer=await pc.createOffer();await pc.setLocalDescription(offer);if(!await send("offer",{description:pc.localDescription?.toJSON(),mode,callerName:window.currentUser.username||window.currentUser.email||"Пользователь"}))throw new Error("offer не записан");setStatus("Вызов…");await sendCallPush()}catch(e){console.error("Ошибка начала звонка:",e);setStatus(e?.name==="NotAllowedError"?"Разрешите микрофон/камеру в браузере":"Не удалось начать звонок");setTimeout(()=>end(false),1800)}}
    async function acceptIncoming(){if(!pendingOffer||!callId)return;try{$("cv2Incoming").style.display="none";$("cv2Controls").style.display="flex";setStatus("Запрашиваем доступ…");await getMedia();buildPeer();await pc.setRemoteDescription(pendingOffer);await flushIce();const answer=await pc.createAnswer();await pc.setLocalDescription(answer);setStatus("Соединение…");await send("answer",{description:pc.localDescription?.toJSON()})}catch(e){console.error("Ошибка принятия звонка:",e);setStatus(e?.name==="NotAllowedError"?"Разрешите микрофон/камеру в браузере":"Не удалось принять звонок");setTimeout(()=>end(true),1800)}}
    async function rejectIncoming(){await send("reject");await end(false)}
    async function end(notify){if(notify&&callId&&peerId)await send("hangup");clearTimer();try{pc?.close()}catch{}pc=null;localStream?.getTracks().forEach(t=>t.stop());localStream=null;remoteStream=null;pendingOffer=null;pendingIce=[];callId=null;peerId=null;role=null;if($("chatCallV2"))$("chatCallV2").classList.remove("open");if($("cv2Remote"))$("cv2Remote").srcObject=null;if($("cv2Local"))$("cv2Local").srcObject=null}
    function toggleMute(){const t=localStream?.getAudioTracks?.()[0];if(!t)return;t.enabled=!t.enabled;$("cv2Mute").textContent=t.enabled?"🎙️":"🔇";$("cv2Mute").classList.toggle("green",!t.enabled)}
    function toggleVideo(){const t=localStream?.getVideoTracks?.()[0];if(!t)return;t.enabled=!t.enabled;$("cv2VideoControl").textContent=t.enabled?"📹":"🚫";$("cv2VideoControl").classList.toggle("green",!t.enabled)}
    async function toggleSpeaker(){const v=$("cv2Remote");if(v&&"setSinkId"in v){try{const d=(await navigator.mediaDevices.enumerateDevices()).find(x=>x.kind==="audiooutput");if(d)await v.setSinkId(d.deviceId)}catch{}}$("cv2Speaker")?.classList.toggle("green")}
    function addButtons(){const header=document.querySelector(".chat-header-actions");if(!header)return;const make=(id,title,modeArg,extra,iconHtml)=>{const b=document.createElement("button");b.id=id;b.type="button";b.title=title;b.setAttribute("aria-label",title);b.className=`chat-call-button ${extra}`;b.innerHTML=iconHtml;b.addEventListener("click",()=>void startCall(modeArg));return b};let audio=$("callAudioButton"),video=$("callVideoButton");if(!video){video=make("callVideoButton","Видеозвонок","video","chat-call-video",`<span class="call-icon-video" aria-hidden="true"></span>`);header.insertBefore(video,header.firstChild)}if(!audio){audio=make("callAudioButton","Аудиозвонок","audio","chat-call-audio",`<span class="call-icon-phone" aria-hidden="true">☎</span>`);header.insertBefore(audio,video.nextSibling)}if(!video.dataset.callBound){video.onclick=()=>void startCall("video");video.dataset.callBound="1"}if(!audio.dataset.callBound){audio.onclick=()=>void startCall("audio");audio.dataset.callBound="1"}}
    async function updateButtons(){
        const audio=$("callAudioButton"),video=$("callVideoButton");
        if(!audio||!video)return;

        const currentItem=document.querySelector(`.chat-item[data-chat-id="${Number(currentChatId||0)}"]`);
        const visible=!!currentItem && currentItem.dataset.chatType==="private";
        const display=visible?"inline-flex":"none";

        audio.style.setProperty("display",display,"important");
        video.style.setProperty("display",display,"important");
    }
    function init(){ensureUi();addButtons();setTimeout(()=>void subscribe(),300);document.addEventListener("click",e=>{if(e.target.closest?.(".chat-item"))setTimeout(()=>{addButtons();void updateButtons()},150)});setTimeout(()=>{addButtons();void updateButtons()},800);if(window.supabaseClient?.auth?.onAuthStateChange)window.supabaseClient.auth.onAuthStateChange(()=>{if(channel){try{window.supabaseClient.removeChannel(channel)}catch{}}channel=null;setTimeout(()=>void subscribe(),100);setTimeout(()=>{addButtons();void updateButtons()},300)})}
    window.startChatCall=startCall;window.endChatCall=end;window.updateChatCallButton=updateButtons;window.updateChatCallButtonVisibility=updateButtons;
    if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
