// =========================================
// Web Push / PWA / установка приложения
// =========================================
const CHAT_VAPID_PUBLIC_KEY="BDiBPq7oIur30bHa0GlYLuNxBwzkph4srXdSHVD2j_rzbJVmxAwXJIKZucYWEgRIXzTAXwHuZv73lEpd5g0h36w";
const CHAT_PUSH_SUBSCRIPTION_KEY="chat_push_subscription";
const CHAT_PUSH_BUTTON_ID="enablePushButton";
const CHAT_INSTALL_BUTTON_ID="installAppButton";
let chatInstallPrompt=null;

function isPushConfigured(){return Boolean(CHAT_VAPID_PUBLIC_KEY&&CHAT_VAPID_PUBLIC_KEY!=="REPLACE_WITH_VAPID_PUBLIC_KEY");}
function urlBase64ToUint8Array(value){var padding="=".repeat((4-(value.length%4))%4),base64=(value+padding).replace(/-/g,"+").replace(/_/g,"/"),raw=atob(base64),out=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function removePushButton(){var b=document.getElementById(CHAT_PUSH_BUTTON_ID);if(b&&b.parentNode)b.parentNode.removeChild(b);}
function removeInstallButton(){var b=document.getElementById(CHAT_INSTALL_BUTTON_ID);if(b&&b.parentNode)b.parentNode.removeChild(b);}

async function registerChatServiceWorker(){if(!(typeof navigator!=="undefined"&&"serviceWorker" in navigator))return null;try{var registration=await navigator.serviceWorker.register("./sw.js",{scope:"./"});try{await registration.update();}catch(error){}await navigator.serviceWorker.ready;return registration;}catch(error){console.error("Не удалось зарегистрировать Service Worker:",error);return null;}}
async function getChatPushUser(){if(window.currentUser&&window.currentUser.id)return window.currentUser;if(!window.supabaseClient)return null;try{var r=await window.supabaseClient.auth.getUser();return r&&r.data&&r.data.user?r.data.user:null;}catch(error){return null;}}
async function saveChatPushSubscription(subscription){if(!subscription||!window.supabaseClient)return false;var user=await getChatPushUser();if(!user||!user.id)return false;var json=subscription.toJSON(),keys=json.keys||{};if(!json.endpoint||!keys.p256dh||!keys.auth)return false;var r=await window.supabaseClient.from("web_push_subscriptions").upsert({user_id:user.id,endpoint:json.endpoint,p256dh:keys.p256dh,auth:keys.auth,updated_at:new Date().toISOString()},{onConflict:"user_id,endpoint"});if(r.error)return false;localStorage.setItem(CHAT_PUSH_SUBSCRIPTION_KEY,JSON.stringify(json));return true;}
async function ensureChatPushSubscription(registration){if(!registration||!isPushConfigured())return null;var existing=await registration.pushManager.getSubscription();if(existing){await saveChatPushSubscription(existing);return existing;}return null;}
async function enableChatPushNotifications(){if(!isPushConfigured())return null;if(!("Notification" in window)||!("PushManager" in window)){alert("Этот браузер не поддерживает Web Push.");return null;}var registration=await registerChatServiceWorker();if(!registration)return null;var permission=Notification.permission;if(permission!=="granted")permission=await Notification.requestPermission();if(permission!=="granted")return null;var subscription=await registration.pushManager.getSubscription()||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(CHAT_VAPID_PUBLIC_KEY)});if(!await saveChatPushSubscription(subscription))return null;localStorage.setItem("chat_push_enabled","1");removePushButton();return subscription;}
async function syncChatPushSubscription(){if(!isPushConfigured()||!window.supabaseClient||!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window)||Notification.permission!=="granted")return null;try{return await ensureChatPushSubscription(await registerChatServiceWorker());}catch(error){return null;}}
async function sendChatPushForMessage(messageId){if(!messageId||!window.supabaseClient)return;try{var r=await window.supabaseClient.functions.invoke("send-message-push",{body:{messageId:messageId}});if(r.error)console.warn("Web Push не отправлен:",r.error);}catch(error){console.warn("Ошибка вызова Web Push:",error);}}

function createPushButton(){if(!isPushConfigured()||document.getElementById(CHAT_PUSH_BUTTON_ID))return;if(!(window.Notification&&window.PushManager&&navigator.serviceWorker))return;if(Notification.permission==="granted")return;var button=document.createElement("button");button.id=CHAT_PUSH_BUTTON_ID;button.type="button";button.textContent="🔔 Включить уведомления";button.style.cssText="position:fixed;left:12px;bottom:12px;z-index:9999;min-height:42px;padding:9px 13px;border:1px solid rgba(255,255,255,.2);border-radius:11px;background:#171412;color:#fff;font-weight:700;font-size:13px;cursor:pointer";button.addEventListener("click",async function(){button.disabled=true;button.textContent="⏳ Подключаем уведомления...";var subscription=await enableChatPushNotifications();if(!subscription){button.disabled=false;button.textContent=Notification.permission==="denied"?"⚠️ Разрешите уведомления в настройках":"🔔 Включить уведомления";}});document.body.appendChild(button);}

function isAppInstalled(){return window.matchMedia&&window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone===true;}
function createInstallButton(){if(isAppInstalled()||!chatInstallPrompt||document.getElementById(CHAT_INSTALL_BUTTON_ID))return;var button=document.createElement("button");button.id=CHAT_INSTALL_BUTTON_ID;button.type="button";button.textContent="📲 Установить приложение";button.style.cssText="position:fixed;right:12px;bottom:12px;z-index:9999;min-height:42px;padding:9px 13px;border:1px solid rgba(255,255,255,.2);border-radius:11px;background:#356b4f;color:#fff;font-weight:700;font-size:13px;cursor:pointer";button.addEventListener("click",async function(){if(!chatInstallPrompt)return;chatInstallPrompt.prompt();var choice=await chatInstallPrompt.userChoice;chatInstallPrompt=null;if(choice&&choice.outcome==="accepted")removeInstallButton();});document.body.appendChild(button);}
window.addEventListener("beforeinstallprompt",function(event){event.preventDefault();chatInstallPrompt=event;createInstallButton();});
window.addEventListener("appinstalled",function(){chatInstallPrompt=null;removeInstallButton();});

async function initChatPush(){await registerChatServiceWorker();await syncChatPushSubscription();createPushButton();createInstallButton();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){void initChatPush();});else void initChatPush();
