plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.vovkat34.chat'
    compileSdk 36

    defaultConfig {
        applicationId 'com.vovkat34.chat'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation platform('com.google.firebase:firebase-bom:34.17.0')
    implementation 'com.google.firebase:firebase-messaging'
}
